# -*- coding: utf-8 -*-
"""naivebayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfLNgjGPzrCxFezBVP6ybG5RpLmRi-2a
"""

import pandas as pd

data =pd.read_csv("/content/data.csv")

data

data.drop(['Produit'] , axis=1,inplace=True)
data.info()

from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
data['Couleur']=Le.fit_transform(data['Couleur'])
data['Taille']=Le.fit_transform(data['Taille'])
data['Matériau']=Le.fit_transform(data['Matériau'])
data['Poids']=Le.fit_transform(data['Poids'])
data['Catégorie']=Le.fit_transform(data['Catégorie'])
data

X= list(zip(data['Couleur'],data['Taille'],data['Matériau'],data['Poids']))
y = data['Catégorie']

X

y

from sklearn.naive_bayes import MultinomialNB # Corrected the typo in the class name from MultinomiaLNB to MultinomialNB

"""Modele **taraitment**"""

bayes = MultinomialNB()
bayes.fit(X,y)

import numpy as np

test = np.array([[2, 0, 1, 1]])

p=bayes.predict(test)
print(p)